### ISSUE TITLE
NPC wanderers

### ISSUE THREAD

**Issue by igorko** [dorkster/flare-engine-next#10]
Migrated from https://github.com/clintbellanger/flare-engine/issues/676

@makrohn wrote
What are the chances we'll ever see NPC wanderers? I know they're not a staple of the genre, but I do think it'd very much liven up some areas - both Laurelia and Frontier Outpost. I've tried using a combination of suppress_hp, threat=0, dmg=0 to mimic NPC wanderers, but they'll still stalk the player if he hits them with an attack, mistakenly trying to talk to them.

I know I can see a LOT of work coming from such a change - instead of just npcs/npcA.txt and images/npcs/npcA.png, we'd also need all eight directions in the .png (instead of possibly a single frame) and probably an animations/npc.txt. BUT, even for a non-wandering NPC, then we could have various NPCs with the same gfx (see refugees in my makrohn FLARE mods) face different directions - and maybe even turn when you talk to them. NPCs who wander would, of course, need all eight directions walking as well - possibly increasing the size of their .png from one 64x64 frame to sixty-four 64x64 frames.

**Comment by igorko** [comment]
How about adding to NPCs the ability to make a party with avatar, like minions and conversion power do? But this would require not only giving NPCs fighting skills but also some engine improvements to know when NPC should enter into party and leave it.

**Comment by igorko** [comment]
Hello avaryone. @dorkster, as I remember wandering NPCs were not merged into flare-engine neither flare-engine-next. And as I remember they were finished by us and have no issues anymore. Can you merge(and recheck) the changes? Maybe it would also be cool to add feaute into main flare-engine? @clintbellanger , how about that?

**Comment by dorkster** [comment]
I've merged it for flare-engine-next. I'm not sure yet if it's worth merging into flare-engine.

**Comment by dorkster** [comment]
I realize this is very late, but I finally got this [merged](https://github.com/flareteam/flare-engine/commit/4b4de90099ed11324bc37c5b7f0abcd1ac404b03) into flare-engine. I had wanted to do some refactoring across the engine to make NPCs based off the Entity class instead of the Enemy class. It just took me quite a while to actually get around to doing it.
