### ISSUE TITLE
Weather support

### ISSUE THREAD

**Issue by igorko** [dorkster/flare-engine-next#24]
Snow and rain, mainly, but also cloud shadows. This should be fast and not hard with SDL2.

**Comment by wolfpirker** [comment]
I'm working on this issue.

I created a fork with my current progress of this feature. 

It's far from finished. 

things implemented in my fork so far:
  * a snow animation 
  * basic classes structure

In the next few weeks I will continue to work on this feature. One of my main intentions with this is to improve my C++ skills with a practical project. I don't have much C++ experience yet.

**Comment by igorko** [comment]
@wolfpirker Nice work. I saw snow in the game :) Some fixes were needed to compile under Windows and some still needed to avoid memory corruption @dorkster As I understand we can merge wolfpirker's work and do fixes in main repo, right? (I saw this was done some time ago)

Also notice for @wolfpirker : we do not use c++ 0x in flare, so avoid new features in the code.

**Comment by igorko** [comment]
@wolfpirker here is diff with my fixes.
https://gist.github.com/igorko/8005917f3ab6bdb9bf66
Just copy text, and paste into txt file, save it with *.diff extension. Then you will be able to apply it to working tree.

Mainly it fixed build under Visual Studio, also fixed dereferencing of invalid iterator, and uncovered crash in destructor (this one just commented out, didn't find where is the actual reason.)

A huge note about OOP feature called Inheritance, At first look I didn't find the reason of making WeatherClimate base class for WeatherManager. You use only enums from WeatherClimate inside of WeatherManager. That means WeatherManager doesn't use any features of WeatherClimate. And furthermore, you put WeatherClimate object into local klima object. Inheritance is used for different purposes. See e.g. here: http://www.tutorialspoint.com/cplusplus/cpp_inheritance.htm

If in future there will be a need to inherit WeatherManager from WeatherClimate, you can do it. But currently there is no need in this, enums just should be located in global space

**Comment by igorko** [comment]
@dorkster can you look into related destructor(see in diff what I mean). This can be caused by our Image class, but hopefully just wrong usage...

**Comment by wolfpirker** [comment]
hey igorko,
thank you for your advice and patch!

I continue to work on this feature the next few weeks, but the progress might be rather slow, due to a new real life occupation of mine. But I still like to and have fun to improve the weather feature further. Now there is also clouds implemented, but the clouds animation is a bit awkward sometimes.

**Comment by igorko** [comment]
@wolfpirker please get new changes/fixes from main repo flare-engine-next/weather branch.
