### ISSUE TITLE
SDL2 Text rendering is less smooth

### ISSUE THREAD

**Issue by dorkster** [dorkster/flare-engine-next#5]
Comparison image (SDL 1.2 is on the left, SDL 2 is on the right):
![sdl1_vs_sdl2](https://f.cloud.github.com/assets/913982/1985465/9c38cec8-843e-11e3-9aba-02db676d3479.png)

**Comment by igorko** [comment]
I guess this is obsolete issue, @dorkster ?

**Comment by dorkster** [comment]
Correct. There's no difference visually between the two renderers now. We might even want to consider using the sdl_hardware renderer by default across the board. (it's the default on Android).
